Generated support matrix + fixed broken build which was caused by installing latest version of 'parallel' on ruby-1.8.7

diff --git a/run-all-tests b/run-all-tests
--- a/run-all-tests
+++ b/run-all-tests
@@ -1,33 +1,57 @@
 #!/bin/bash
 
-REPORT=test-report.md
+REPORT=SUPPORTED_VERSIONS.MD
 
 check() {
-	local ruby_version=$1
-	local puppet_version=$2
+    local ruby_version=$1
+    local puppet_version=$2
 
-	report_string="ruby_version=$ruby_version puppet_version=$puppet_version"
+    report_string="ruby_version=$ruby_version puppet_version=$puppet_version"
 
-	export PUPPET_VERSION=$puppet_version
-	rm -f Gemfile.lock
-	rbenv global $ruby_version
+    echo "==> Running ${report_string}"
 
-	bundle install
-	bundle exec rake test
+    export PUPPET_VERSION=$puppet_version
+    rm -f Gemfile.lock
+    rbenv global $ruby_version
 
+    bundle -h 2>&1 1>/dev/null
+    if [ $? -ne 0 ]; then
+      gem install bundler
+    fi
 
-	if [ $? -ne 0 ]; then
-		echo "FAILED $report_string" >> $REPORT
-	else
-		echo "SUCCEEDED $report_string" >> $REPORT
-	fi
+    bundle install
+    bundle exec rake test
+
+    if [ $? -ne 0 ]; then
+        echo "|${ruby_version}|${puppet_version}|FAILED|" >> $REPORT
+    else
+        echo "|${ruby_version}|${puppet_version}|**SUPPORTED**|" >> $REPORT
+    fi
 }
 
-echo "" > $REPORT
+unsupported() {
+    local ruby_version=$1
+    local puppet_version=$2
 
-check 1.9.3-p551 3.0.2
-check 1.9.3-p551 3.7.3
-check 1.9.3-p551 4.0.0
-check 1.9.3-p551 4.1.0
+    echo "|${ruby_version}|${puppet_version}|UNSUPPORTED|" >> $REPORT
+}
+
+echo -e "| Ruby Version | Puppet Version | Status |\n|---|---|---|" > $REPORT
+
+if [ $# -gt 0 ]; then
+  check $*
+else
+  check 1.8.7-p374 3.0.2
+  check 1.8.7-p374 3.7.3
+  unsupported 1.8.7-p374 4.0.0
+  unsupported 1.8.7-p374 4.1.0
+
+  check 1.9.3-p551 3.0.2
+  check 1.9.3-p551 3.7.3
+  check 1.9.3-p551 4.0.0
+  check 1.9.3-p551 4.1.0
+fi
+
+echo "*generated at `date`*" >> $REPORT
 
 cat $REPORT
